---
title: Inverting matrices of pairwise minima
topics: [mathematics, statistics]
linkSource: no
summary: |
  I describe the inverse of the matrix of pairwise minima.
  This matrix arises when learning from data generated by a Wiener process.
---

```{r echo = F}
a = 2 ^ (0:4)
# a = 1:5
n = length(a)
A = matrix(0, n, n)
for (i in 1:n) {
  for (j in 1:n) {
    A[i, j] = a[min(i, j)]
  }
}

Ainv = solve(A)

mat2tex = function(mat) {
  row2tex = \(x) paste(x, collapse = ' & ')
  rows = paste(apply(mat, 1, row2tex), '\\\\')
  res = paste(c('\\begin{bmatrix}', rows, '\\end{bmatrix}'), collapse = '\n')
  res
}
```

Let $0<x_1<x_2<\ldots<x_n$ and let $A$ be the symmetric $n\times n$ matrix with ${ij}^\text{th}$ entry $A_{ij}=\min\{x_i,x_j\}$.[^name]
This matrix has linearly independent columns and so is invertible.
Its inverse $A^{-1}$ is symmetric, [tridiagonal](https://en.wikipedia.org/wiki/Tridiagonal_matrix), and has ${ij}^\text{th}$ entry
$$[A^{-1}]_{ij}=\begin{cases}
\frac{1}{x_1}+\frac{1}{x_2-x_1} & \text{if}\ i=j=1 \\
\frac{1}{x_i-x_{i-1}}+\frac{1}{x_{i+1}-x_i} & \text{if}\ 1<i=j<n \\
\frac{1}{x_n-x_{n-1}} & \text{if}\ i=j=n \\
-\frac{1}{x_j-x_i} & \text{if}\ i=j-1 \\
-\frac{1}{x_i-x_j} & \text{if}\ i=j+1 \\
0 & \text{otherwise}.
\end{cases}$$
For example, if $x_i=2^{i-1}$ for each $i\le n=5$ then
$$A=`r mat2tex(A)`$$
and
$$A^{-1}=`r mat2tex(round(Ainv, 3))`$$
You may wonder: why is this useful?
Suppose I observe data $\{(x_i,y_i)\}_{i=1}^n$, where the function $f:[0,\infty)\to\mathbb{R}$ mapping regressors $x_i\ge0$ to outcomes $y_i=f(x_i)$ is the realization of a [Wiener process](https://en.wikipedia.org/wiki/Wiener_process).
I use these data to estimate some value $f(x)$ via [Bayesian regression](https://en.wikipedia.org/wiki/Bayesian_linear_regression).
My estimate depends on the inverse of the covariance matrix for the outcome vector $y=(y_1,y_2,\ldots,y_n)$.
This matrix has ${ij}^\text{th}$ entry $\min\{x_i,x_j\}$, so I can compute its inverse using the expression above.

[^name]: [Let me know](https://mathoverflow.net/questions/453045/is-there-a-name-for-this-family-of-matrices) if the family of such matrices has a name!
